- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable'

- name: Install nginx
  action: apt pkg=nginx-extras state=installed update_cache=true

- name: Disable default site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
